/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TiffinServicesNearAllenRouteImport } from './routes/tiffin-services-near-allen'
import { Route as TiffinServicesNearMotionRouteImport } from './routes/tiffin-services-near-motion'
import { Route as TiffinServicesNearPhysicsWallahRouteImport } from './routes/tiffin-services-near-physics-wallah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TiffinServicesNearAllenRoute = TiffinServicesNearAllenRouteImport.update({
  id: '/tiffin-services-near-allen',
  path: '/tiffin-services-near-allen',
  getParentRoute: () => rootRouteImport,
} as any)
const TiffinServicesNearMotionRoute =
  TiffinServicesNearMotionRouteImport.update({
    id: '/tiffin-services-near-motion',
    path: '/tiffin-services-near-motion',
    getParentRoute: () => rootRouteImport,
  } as any)
const TiffinServicesNearPhysicsWallahRoute =
  TiffinServicesNearPhysicsWallahRouteImport.update({
    id: '/tiffin-services-near-physics-wallah',
    path: '/tiffin-services-near-physics-wallah',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tiffin-services-near-allen': typeof TiffinServicesNearAllenRoute
  '/tiffin-services-near-motion': typeof TiffinServicesNearMotionRoute
  '/tiffin-services-near-physics-wallah': typeof TiffinServicesNearPhysicsWallahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tiffin-services-near-allen': typeof TiffinServicesNearAllenRoute
  '/tiffin-services-near-motion': typeof TiffinServicesNearMotionRoute
  '/tiffin-services-near-physics-wallah': typeof TiffinServicesNearPhysicsWallahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tiffin-services-near-allen': typeof TiffinServicesNearAllenRoute
  '/tiffin-services-near-motion': typeof TiffinServicesNearMotionRoute
  '/tiffin-services-near-physics-wallah': typeof TiffinServicesNearPhysicsWallahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/tiffin-services-near-allen'
    | '/tiffin-services-near-motion'
    | '/tiffin-services-near-physics-wallah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/tiffin-services-near-allen'
    | '/tiffin-services-near-motion'
    | '/tiffin-services-near-physics-wallah'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy'
    | '/terms'
    | '/tiffin-services-near-allen'
    | '/tiffin-services-near-motion'
    | '/tiffin-services-near-physics-wallah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TiffinServicesNearAllenRoute: typeof TiffinServicesNearAllenRoute
  TiffinServicesNearMotionRoute: typeof TiffinServicesNearMotionRoute
  TiffinServicesNearPhysicsWallahRoute: typeof TiffinServicesNearPhysicsWallahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin-services-near-allen': {
      id: '/tiffin-services-near-allen'
      path: '/tiffin-services-near-allen'
      fullPath: '/tiffin-services-near-allen'
      preLoaderRoute: typeof TiffinServicesNearAllenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin-services-near-motion': {
      id: '/tiffin-services-near-motion'
      path: '/tiffin-services-near-motion'
      fullPath: '/tiffin-services-near-motion'
      preLoaderRoute: typeof TiffinServicesNearMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin-services-near-physics-wallah': {
      id: '/tiffin-services-near-physics-wallah'
      path: '/tiffin-services-near-physics-wallah'
      fullPath: '/tiffin-services-near-physics-wallah'
      preLoaderRoute: typeof TiffinServicesNearPhysicsWallahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TiffinServicesNearAllenRoute: TiffinServicesNearAllenRoute,
  TiffinServicesNearMotionRoute: TiffinServicesNearMotionRoute,
  TiffinServicesNearPhysicsWallahRoute: TiffinServicesNearPhysicsWallahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
