/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KakadeoSurvivalGuideRouteImport } from './routes/kakadeo-survival-guide'
import { Route as KanpurStudentCouncilRouteImport } from './routes/kanpur-student-council'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TiffinServicesNearAllenRouteImport } from './routes/tiffin-services-near-allen'
import { Route as TiffinServicesNearMotionRouteImport } from './routes/tiffin-services-near-motion'
import { Route as TiffinServicesNearPhysicsWallahRouteImport } from './routes/tiffin-services-near-physics-wallah'
import { Route as ApiUpdateKycRouteImport } from './routes/api.updateKyc'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as HostDashboardRouteImport } from './routes/host.dashboard'
import { Route as HostLoginRouteImport } from './routes/host.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KakadeoSurvivalGuideRoute = KakadeoSurvivalGuideRouteImport.update({
  id: '/kakadeo-survival-guide',
  path: '/kakadeo-survival-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const KanpurStudentCouncilRoute = KanpurStudentCouncilRouteImport.update({
  id: '/kanpur-student-council',
  path: '/kanpur-student-council',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TiffinServicesNearAllenRoute = TiffinServicesNearAllenRouteImport.update({
  id: '/tiffin-services-near-allen',
  path: '/tiffin-services-near-allen',
  getParentRoute: () => rootRouteImport,
} as any)
const TiffinServicesNearMotionRoute =
  TiffinServicesNearMotionRouteImport.update({
    id: '/tiffin-services-near-motion',
    path: '/tiffin-services-near-motion',
    getParentRoute: () => rootRouteImport,
  } as any)
const TiffinServicesNearPhysicsWallahRoute =
  TiffinServicesNearPhysicsWallahRouteImport.update({
    id: '/tiffin-services-near-physics-wallah',
    path: '/tiffin-services-near-physics-wallah',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUpdateKycRoute = ApiUpdateKycRouteImport.update({
  id: '/api/updateKyc',
  path: '/api/updateKyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/host/dashboard',
  path: '/host/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostLoginRoute = HostLoginRouteImport.update({
  id: '/host/login',
  path: '/host/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kakadeo-survival-guide': typeof KakadeoSurvivalGuideRoute
  '/kanpur-student-council': typeof KanpurStudentCouncilRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tiffin-services-near-allen': typeof TiffinServicesNearAllenRoute
  '/tiffin-services-near-motion': typeof TiffinServicesNearMotionRoute
  '/tiffin-services-near-physics-wallah': typeof TiffinServicesNearPhysicsWallahRoute
  '/api/updateKyc': typeof ApiUpdateKycRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/login': typeof HostLoginRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kakadeo-survival-guide': typeof KakadeoSurvivalGuideRoute
  '/kanpur-student-council': typeof KanpurStudentCouncilRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tiffin-services-near-allen': typeof TiffinServicesNearAllenRoute
  '/tiffin-services-near-motion': typeof TiffinServicesNearMotionRoute
  '/tiffin-services-near-physics-wallah': typeof TiffinServicesNearPhysicsWallahRoute
  '/api/updateKyc': typeof ApiUpdateKycRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/login': typeof HostLoginRoute
  '/host': typeof HostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kakadeo-survival-guide': typeof KakadeoSurvivalGuideRoute
  '/kanpur-student-council': typeof KanpurStudentCouncilRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tiffin-services-near-allen': typeof TiffinServicesNearAllenRoute
  '/tiffin-services-near-motion': typeof TiffinServicesNearMotionRoute
  '/tiffin-services-near-physics-wallah': typeof TiffinServicesNearPhysicsWallahRoute
  '/api/updateKyc': typeof ApiUpdateKycRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/login': typeof HostLoginRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kakadeo-survival-guide'
    | '/kanpur-student-council'
    | '/privacy'
    | '/terms'
    | '/tiffin-services-near-allen'
    | '/tiffin-services-near-motion'
    | '/tiffin-services-near-physics-wallah'
    | '/api/updateKyc'
    | '/host/dashboard'
    | '/host/login'
    | '/host/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/kakadeo-survival-guide'
    | '/kanpur-student-council'
    | '/privacy'
    | '/terms'
    | '/tiffin-services-near-allen'
    | '/tiffin-services-near-motion'
    | '/tiffin-services-near-physics-wallah'
    | '/api/updateKyc'
    | '/host/dashboard'
    | '/host/login'
    | '/host'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kakadeo-survival-guide'
    | '/kanpur-student-council'
    | '/privacy'
    | '/terms'
    | '/tiffin-services-near-allen'
    | '/tiffin-services-near-motion'
    | '/tiffin-services-near-physics-wallah'
    | '/api/updateKyc'
    | '/host/dashboard'
    | '/host/login'
    | '/host/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  KakadeoSurvivalGuideRoute: typeof KakadeoSurvivalGuideRoute
  KanpurStudentCouncilRoute: typeof KanpurStudentCouncilRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TiffinServicesNearAllenRoute: typeof TiffinServicesNearAllenRoute
  TiffinServicesNearMotionRoute: typeof TiffinServicesNearMotionRoute
  TiffinServicesNearPhysicsWallahRoute: typeof TiffinServicesNearPhysicsWallahRoute
  ApiUpdateKycRoute: typeof ApiUpdateKycRoute
  HostDashboardRoute: typeof HostDashboardRoute
  HostLoginRoute: typeof HostLoginRoute
  HostIndexRoute: typeof HostIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kakadeo-survival-guide': {
      id: '/kakadeo-survival-guide'
      path: '/kakadeo-survival-guide'
      fullPath: '/kakadeo-survival-guide'
      preLoaderRoute: typeof KakadeoSurvivalGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanpur-student-council': {
      id: '/kanpur-student-council'
      path: '/kanpur-student-council'
      fullPath: '/kanpur-student-council'
      preLoaderRoute: typeof KanpurStudentCouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin-services-near-allen': {
      id: '/tiffin-services-near-allen'
      path: '/tiffin-services-near-allen'
      fullPath: '/tiffin-services-near-allen'
      preLoaderRoute: typeof TiffinServicesNearAllenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin-services-near-motion': {
      id: '/tiffin-services-near-motion'
      path: '/tiffin-services-near-motion'
      fullPath: '/tiffin-services-near-motion'
      preLoaderRoute: typeof TiffinServicesNearMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiffin-services-near-physics-wallah': {
      id: '/tiffin-services-near-physics-wallah'
      path: '/tiffin-services-near-physics-wallah'
      fullPath: '/tiffin-services-near-physics-wallah'
      preLoaderRoute: typeof TiffinServicesNearPhysicsWallahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/updateKyc': {
      id: '/api/updateKyc'
      path: '/api/updateKyc'
      fullPath: '/api/updateKyc'
      preLoaderRoute: typeof ApiUpdateKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/dashboard': {
      id: '/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/login': {
      id: '/host/login'
      path: '/host/login'
      fullPath: '/host/login'
      preLoaderRoute: typeof HostLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  KakadeoSurvivalGuideRoute: KakadeoSurvivalGuideRoute,
  KanpurStudentCouncilRoute: KanpurStudentCouncilRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TiffinServicesNearAllenRoute: TiffinServicesNearAllenRoute,
  TiffinServicesNearMotionRoute: TiffinServicesNearMotionRoute,
  TiffinServicesNearPhysicsWallahRoute: TiffinServicesNearPhysicsWallahRoute,
  ApiUpdateKycRoute: ApiUpdateKycRoute,
  HostDashboardRoute: HostDashboardRoute,
  HostLoginRoute: HostLoginRoute,
  HostIndexRoute: HostIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
